armor = true

[config]
"modules/private/private.toml" = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMHjHjJ/vMoD3LId4IskuD9A6GwyTQXzt61IEq3/paul paulmiro@newton",
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINirIGaLp4nLyJ4JUbCoknq5uqmp59uOfBrig0iW/mor paulmiro@morse",
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINamsWVM0+zxXxUh5K1ww0GrdleakE3X8QSMJ+0b/btr paulmiro@leibniz",
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGKn+lCU7J7iNEhsCVK8chXmqeGsIAlbqhwbY8Rq/bll paulmiro@bell-avf",
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIESZxtxQOpcoxKjJO5f6XlVDmUSG7ZYz1fN5dIqi/tur paulmiro@turing",
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIq7MvzwppeaeZKiAZD2ioW6MB7wLClX4H78kO72/bak paulmiro@backus",
    "age1wxfa9m4evtrwwvyxalagjyquuznmmdh2p0j4fqkvrpcq2emudycs90peck",
]
